CREATE TABLE `agreements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`publicToken` varchar(32) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientOwnerName` varchar(255) NOT NULL,
	`contactNumber` varchar(64) NOT NULL,
	`email` varchar(320) NOT NULL,
	`address` text NOT NULL,
	`noOfStudents` int NOT NULL,
	`perStudentPrice` decimal(12,2) NOT NULL,
	`noOfYearPlan` int NOT NULL,
	`startDate` varchar(32) NOT NULL,
	`endDate` varchar(32) NOT NULL,
	`totalPrice` decimal(14,2) NOT NULL,
	`description` text,
	`status` enum('Pending','Approved','Rejected') NOT NULL DEFAULT 'Pending',
	`signatureUrl` text,
	`signatureKey` varchar(512),
	`signatureDate` varchar(32),
	`decidedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agreements_id` PRIMARY KEY(`id`),
	CONSTRAINT `agreements_publicToken_unique` UNIQUE(`publicToken`)
);
