CREATE TABLE `quotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`quotationNumber` varchar(32) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientAddress` text NOT NULL,
	`clientContact` varchar(64) NOT NULL,
	`clientEmail` varchar(320),
	`clientGst` varchar(32),
	`quotationDate` varchar(32) NOT NULL,
	`validityDays` int NOT NULL DEFAULT 15,
	`companyGst` varchar(32) NOT NULL,
	`companyAddress` text NOT NULL,
	`itemsJson` text NOT NULL,
	`subtotal` decimal(14,2) NOT NULL,
	`gstRate` decimal(5,2) NOT NULL,
	`gstAmount` decimal(14,2) NOT NULL,
	`grandTotal` decimal(14,2) NOT NULL,
	`terms` text,
	`scannerUrl` text,
	`scannerKey` varchar(512),
	`signatureUrl` text,
	`signatureKey` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotations_id` PRIMARY KEY(`id`),
	CONSTRAINT `quotations_quotationNumber_unique` UNIQUE(`quotationNumber`)
);
