CREATE TABLE `invoiceSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`companyGst` varchar(32) NOT NULL,
	`companyAddress` text NOT NULL,
	`invoicePrefix` varchar(24) NOT NULL DEFAULT 'INV',
	`invoiceNumberStart` int NOT NULL DEFAULT 1,
	`invoiceNumberNext` int NOT NULL DEFAULT 1,
	`gstRate` decimal(5,2) NOT NULL DEFAULT '18.00',
	`gstMode` enum('inclusive','exclusive') NOT NULL DEFAULT 'exclusive',
	`defaultDueDays` int NOT NULL DEFAULT 15,
	`terms` text NOT NULL,
	`accountCompanyName` varchar(255),
	`accountNumber` varchar(128),
	`accountIfsc` varchar(64),
	`accountBranch` varchar(255),
	`logoUrl` text,
	`logoKey` varchar(512),
	`signatureUrl` text,
	`signatureKey` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoiceSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoiceSettings_ownerId_unique` UNIQUE(`ownerId`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`invoiceNumber` varchar(32) NOT NULL,
	`status` enum('Draft','Sent','Paid','Cancelled') NOT NULL DEFAULT 'Draft',
	`clientName` varchar(255) NOT NULL,
	`clientAddress` text NOT NULL,
	`clientContact` varchar(64),
	`clientEmail` varchar(320),
	`clientGst` varchar(32),
	`invoiceDate` varchar(32) NOT NULL,
	`dueDate` varchar(32) NOT NULL,
	`itemsJson` text NOT NULL,
	`subtotal` decimal(14,2) NOT NULL,
	`gstRate` decimal(5,2) NOT NULL,
	`gstMode` enum('inclusive','exclusive') NOT NULL DEFAULT 'exclusive',
	`gstAmount` decimal(14,2) NOT NULL,
	`grandTotal` decimal(14,2) NOT NULL,
	`notes` text,
	`terms` text,
	`companyGst` varchar(32) NOT NULL,
	`companyAddress` text NOT NULL,
	`accountCompanyName` varchar(255),
	`accountNumber` varchar(128),
	`accountIfsc` varchar(64),
	`accountBranch` varchar(255),
	`logoUrl` text,
	`logoKey` varchar(512),
	`signatureUrl` text,
	`signatureKey` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoices_invoiceNumber_unique` UNIQUE(`invoiceNumber`)
);
--> statement-breakpoint
CREATE TABLE `receiptSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`companyGst` varchar(32) NOT NULL,
	`companyAddress` text NOT NULL,
	`receiptPrefix` varchar(24) NOT NULL DEFAULT 'RCT',
	`receiptNumberStart` int NOT NULL DEFAULT 1,
	`receiptNumberNext` int NOT NULL DEFAULT 1,
	`terms` text NOT NULL,
	`accountCompanyName` varchar(255),
	`accountNumber` varchar(128),
	`accountIfsc` varchar(64),
	`accountBranch` varchar(255),
	`logoUrl` text,
	`logoKey` varchar(512),
	`signatureUrl` text,
	`signatureKey` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `receiptSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `receiptSettings_ownerId_unique` UNIQUE(`ownerId`)
);
--> statement-breakpoint
CREATE TABLE `receipts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`receiptNumber` varchar(32) NOT NULL,
	`status` enum('Issued','Cancelled') NOT NULL DEFAULT 'Issued',
	`clientName` varchar(255) NOT NULL,
	`clientAddress` text NOT NULL,
	`clientContact` varchar(64),
	`clientEmail` varchar(320),
	`receiptDate` varchar(32) NOT NULL,
	`paymentDate` varchar(32) NOT NULL,
	`amount` decimal(14,2) NOT NULL,
	`paymentMode` enum('Cash','UPI','Bank Transfer','Card','Cheque','Other') NOT NULL DEFAULT 'Bank Transfer',
	`transactionReference` varchar(128),
	`receivedFor` varchar(255) NOT NULL,
	`notes` text,
	`terms` text,
	`companyGst` varchar(32) NOT NULL,
	`companyAddress` text NOT NULL,
	`accountCompanyName` varchar(255),
	`accountNumber` varchar(128),
	`accountIfsc` varchar(64),
	`accountBranch` varchar(255),
	`logoUrl` text,
	`logoKey` varchar(512),
	`signatureUrl` text,
	`signatureKey` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `receipts_id` PRIMARY KEY(`id`),
	CONSTRAINT `receipts_receiptNumber_unique` UNIQUE(`receiptNumber`)
);
