CREATE TABLE `clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int,
	`clientId` varchar(64) NOT NULL,
	`ownerId` int NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientOwnerName` varchar(255) NOT NULL,
	`instituteType` enum('School','College','Academy') NOT NULL DEFAULT 'School',
	`branchCoverage` enum('individual','multiple') NOT NULL DEFAULT 'individual',
	`branchCount` int NOT NULL DEFAULT 1,
	`contactNumber` varchar(64) NOT NULL,
	`email` varchar(320) NOT NULL,
	`address` text NOT NULL,
	`noOfStudents` int NOT NULL DEFAULT 0,
	`pricingMode` enum('perStudent','package') NOT NULL DEFAULT 'perStudent',
	`perStudentPrice` decimal(12,2),
	`packagePrice` decimal(14,2),
	`noOfYearPlan` int NOT NULL DEFAULT 1,
	`startDate` varchar(32) NOT NULL,
	`endDate` varchar(32) NOT NULL,
	`session` varchar(16) NOT NULL DEFAULT '2026-2027',
	`totalPrice` decimal(14,2) NOT NULL DEFAULT '0.00',
	`description` text,
	`logoUrl` text,
	`logoKey` varchar(512),
	`status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clients_id` PRIMARY KEY(`id`),
	CONSTRAINT `clients_clientId_unique` UNIQUE(`clientId`)
);
