CREATE TABLE `clientProducts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`clientId` varchar(64) NOT NULL,
	`projectId` int,
	`productName` varchar(255) NOT NULL,
	`description` text,
	`quantity` decimal(12,2) NOT NULL DEFAULT '1.00',
	`unitPrice` decimal(14,2) NOT NULL,
	`gstRate` decimal(5,2) NOT NULL DEFAULT '0.00',
	`gstMode` enum('inclusive','exclusive') NOT NULL DEFAULT 'exclusive',
	`subtotal` decimal(14,2) NOT NULL,
	`gstAmount` decimal(14,2) NOT NULL,
	`totalAmount` decimal(14,2) NOT NULL,
	`paidAmount` decimal(14,2) NOT NULL DEFAULT '0.00',
	`paymentStatus` enum('Pending','Partially Paid','Paid') NOT NULL DEFAULT 'Pending',
	`dueDate` varchar(32),
	`paymentDate` varchar(32),
	`paymentMode` varchar(64),
	`transactionReference` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clientProducts_id` PRIMARY KEY(`id`)
);
