import { boolean, int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
  companyLogoUrl: text("companyLogoUrl"),
  companyLogoKey: varchar("companyLogoKey", { length: 512 }),
  companyName: varchar("companyName", { length: 255 }),
  serviceCaption: varchar("serviceCaption", { length: 255 }),
  footerCompanyName: varchar("footerCompanyName", { length: 255 }),
  sessionMode: mysqlEnum("sessionMode", ["all", "single"]).default("single").notNull(),
  currentSession: varchar("currentSession", { length: 16 }).default("2026-2027").notNull(),
});

export const sessions = mysqlTable("sessions", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull(),
  sessionLabel: varchar("sessionLabel", { length: 16 }).notNull(),
  startDate: varchar("startDate", { length: 32 }).notNull(),
  endDate: varchar("endDate", { length: 32 }).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const quotationSettings = mysqlTable("quotationSettings", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull().unique(),
  companyGst: varchar("companyGst", { length: 32 }).notNull(),
  companyAddress: text("companyAddress").notNull(),
  validityDays: int("validityDays").default(15).notNull(),
  gstRate: decimal("gstRate", { precision: 5, scale: 2 }).default("18.00").notNull(),
  gstMode: mysqlEnum("gstMode", ["inclusive", "exclusive"]).default("exclusive").notNull(),
  quotationPrefix: varchar("quotationPrefix", { length: 24 }).default("QT").notNull(),
  invoiceNumberStart: int("invoiceNumberStart").default(129).notNull(),
  invoiceNumberNext: int("invoiceNumberNext").default(129).notNull(),
  terms: text("terms").notNull(),
  productsJson: text("productsJson").notNull(),
  logoUrl: text("logoUrl"),
  logoKey: varchar("logoKey", { length: 512 }),
  scannerUrl: text("scannerUrl"),
  scannerKey: varchar("scannerKey", { length: 512 }),
  signatureUrl: text("signatureUrl"),
  signatureKey: varchar("signatureKey", { length: 512 }),
  accountCompanyName: varchar("accountCompanyName", { length: 255 }),
  accountNumber: varchar("accountNumber", { length: 128 }),
  accountIfsc: varchar("accountIfsc", { length: 64 }),
  accountBranch: varchar("accountBranch", { length: 255 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const quotationSettingsData = mysqlTable("quotationSettingsData", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull().unique(),
  settingsJson: text("settingsJson").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const profileSettingsData = mysqlTable("profileSettingsData", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull().unique(),
  profileJson: text("profileJson").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const quotationEditHistory = mysqlTable("quotationEditHistory", {
  id: int("id").autoincrement().primaryKey(),
  quotationId: int("quotationId").notNull(),
  ownerId: int("ownerId").notNull(),
  editedBy: int("editedBy").notNull(),
  editedByName: varchar("editedByName", { length: 255 }).notNull(),
  editedAt: timestamp("editedAt").defaultNow().notNull(),
  snapshotJson: text("snapshotJson").notNull(),
});

export const quotations = mysqlTable("quotations", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull(),
  quotationNumber: varchar("quotationNumber", { length: 32 }).notNull().unique(),
  invoiceNumber: varchar("invoiceNumber", { length: 32 }).unique(),
  estimationNumber: int("estimationNumber").default(1).notNull(),
  status: mysqlEnum("status", ["Awaiting", "Success", "Closed"]).default("Awaiting").notNull(),
  clientName: varchar("clientName", { length: 255 }).notNull(),
  clientAddress: text("clientAddress").notNull(),
  clientContact: varchar("clientContact", { length: 64 }).notNull(),
  clientEmail: varchar("clientEmail", { length: 320 }),
  clientGst: varchar("clientGst", { length: 32 }),
  quotationDate: varchar("quotationDate", { length: 32 }).notNull(),
  validityDays: int("validityDays").default(15).notNull(),
  companyGst: varchar("companyGst", { length: 32 }).notNull(),
  companyAddress: text("companyAddress").notNull(),
  itemsJson: text("itemsJson").notNull(),
  subtotal: decimal("subtotal", { precision: 14, scale: 2 }).notNull(),
  gstRate: decimal("gstRate", { precision: 5, scale: 2 }).notNull(),
  gstMode: mysqlEnum("gstMode", ["inclusive", "exclusive"]).default("exclusive").notNull(),
  gstAmount: decimal("gstAmount", { precision: 14, scale: 2 }).notNull(),
  grandTotal: decimal("grandTotal", { precision: 14, scale: 2 }).notNull(),
  terms: text("terms"),
  logoUrl: text("logoUrl"),
  logoKey: varchar("logoKey", { length: 512 }),
  scannerUrl: text("scannerUrl"),
  scannerKey: varchar("scannerKey", { length: 512 }),
  signatureUrl: text("signatureUrl"),
  signatureKey: varchar("signatureKey", { length: 512 }),
  accountCompanyName: varchar("accountCompanyName", { length: 255 }),
  accountNumber: varchar("accountNumber", { length: 128 }),
  accountIfsc: varchar("accountIfsc", { length: 64 }),
  accountBranch: varchar("accountBranch", { length: 255 }),
  lastEditedBy: int("lastEditedBy"),
  lastEditedByName: varchar("lastEditedByName", { length: 255 }),
  lastEditedAt: timestamp("lastEditedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const projects = mysqlTable("projects", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  clientIdPrefix: varchar("clientIdPrefix", { length: 24 }).notNull(),
  isMain: boolean("isMain").default(false).notNull(),
  clientIdStart: int("clientIdStart").default(1).notNull(),
  nextClientId: int("nextClientId").default(1).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const clients = mysqlTable("clients", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  clientId: varchar("clientId", { length: 64 }).notNull().unique(),
  ownerId: int("ownerId").notNull(),
  clientName: varchar("clientName", { length: 255 }).notNull(),
  clientOwnerName: varchar("clientOwnerName", { length: 255 }).notNull(),
  instituteType: mysqlEnum("instituteType", ["School", "College", "Academy"]).default("School").notNull(),
  branchCoverage: mysqlEnum("branchCoverage", ["individual", "multiple"]).default("individual").notNull(),
  branchCount: int("branchCount").default(1).notNull(),
  contactNumber: varchar("contactNumber", { length: 64 }).notNull(),
  email: varchar("email", { length: 320 }).notNull(),
  address: text("address").notNull(),
  noOfStudents: int("noOfStudents").notNull().default(0),
  pricingMode: mysqlEnum("pricingMode", ["perStudent", "package"]).default("perStudent").notNull(),
  perStudentPrice: decimal("perStudentPrice", { precision: 12, scale: 2 }),
  packagePrice: decimal("packagePrice", { precision: 14, scale: 2 }),
  noOfYearPlan: int("noOfYearPlan").notNull().default(1),
  startDate: varchar("startDate", { length: 32 }).notNull(),
  endDate: varchar("endDate", { length: 32 }).notNull(),
  session: varchar("session", { length: 16 }).default("2026-2027").notNull(),
  totalPrice: decimal("totalPrice", { precision: 14, scale: 2 }).notNull().default("0.00"),
  price: decimal("price", { precision: 14, scale: 2 }).notNull().default("0.00"),
  gstRate: decimal("gstRate", { precision: 5, scale: 2 }).notNull().default("18.00"),
  gstMode: mysqlEnum("gstMode", ["inclusive", "exclusive"]).notNull().default("exclusive"),
  gstAmount: decimal("gstAmount", { precision: 14, scale: 2 }).notNull().default("0.00"),
  description: text("description"),
  logoUrl: text("logoUrl"),
  logoKey: varchar("logoKey", { length: 512 }),
  status: mysqlEnum("status", ["Active", "Inactive", "Hold", "Cancelled", "Renewal", "Extended", "Closed"]).default("Active").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const agreements = mysqlTable("agreements", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  clientId: varchar("clientId", { length: 64 }),
  ownerId: int("ownerId").notNull(),
  publicToken: varchar("publicToken", { length: 32 }).notNull().unique(),
  clientName: varchar("clientName", { length: 255 }).notNull(),
  clientOwnerName: varchar("clientOwnerName", { length: 255 }).notNull(),
  instituteType: mysqlEnum("instituteType", ["School", "College", "Academy"]).default("School").notNull(),
  branchCoverage: mysqlEnum("branchCoverage", ["individual", "multiple"]).default("individual").notNull(),
  branchCount: int("branchCount").default(1).notNull(),
  contactNumber: varchar("contactNumber", { length: 64 }).notNull(),
  email: varchar("email", { length: 320 }).notNull(),
  address: text("address").notNull(),
  noOfStudents: int("noOfStudents").notNull(),
  pricingMode: mysqlEnum("pricingMode", ["perStudent", "package"]).default("perStudent").notNull(),
  perStudentPrice: decimal("perStudentPrice", { precision: 12, scale: 2 }),
  packagePrice: decimal("packagePrice", { precision: 14, scale: 2 }),
  noOfYearPlan: int("noOfYearPlan").notNull(),
  startDate: varchar("startDate", { length: 32 }).notNull(),
  endDate: varchar("endDate", { length: 32 }).notNull(),
  session: varchar("session", { length: 16 }).default("2026-2027").notNull(),
  subtotal: decimal("subtotal", { precision: 14, scale: 2 }).notNull().default("0.00"),
  gstRate: decimal("gstRate", { precision: 5, scale: 2 }).notNull().default("18.00"),
  gstMode: mysqlEnum("gstMode", ["inclusive", "exclusive"]).notNull().default("exclusive"),
  gstAmount: decimal("gstAmount", { precision: 14, scale: 2 }).notNull().default("0.00"),
  totalPrice: decimal("totalPrice", { precision: 14, scale: 2 }).notNull(),
  description: text("description"),
  logoUrl: text("logoUrl"),
  logoKey: varchar("logoKey", { length: 512 }),
  status: mysqlEnum("status", ["Pending", "Approved", "Rejected"]).default("Pending").notNull(),
  clientStatus: mysqlEnum("clientStatus", ["Active", "Inactive", "Hold", "Cancelled", "Renewal", "Extended", "Closed"]),
  renewalOfAgreementId: int("renewalOfAgreementId"),
  renewalType: mysqlEnum("renewalType", ["continuous", "sixMonths", "oneYear"]),
  signatureUrl: text("signatureUrl"),
  signatureKey: varchar("signatureKey", { length: 512 }),
  signatureDate: varchar("signatureDate", { length: 32 }),
  decidedAt: timestamp("decidedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const invoiceSettings = mysqlTable("invoiceSettings", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull().unique(),
  companyGst: varchar("companyGst", { length: 32 }).notNull(),
  companyAddress: text("companyAddress").notNull(),
  invoicePrefix: varchar("invoicePrefix", { length: 24 }).default("INV").notNull(),
  invoiceNumberStart: int("invoiceNumberStart").default(1).notNull(),
  invoiceNumberNext: int("invoiceNumberNext").default(1).notNull(),
  gstRate: decimal("gstRate", { precision: 5, scale: 2 }).default("18.00").notNull(),
  gstMode: mysqlEnum("gstMode", ["inclusive", "exclusive"]).default("exclusive").notNull(),
  defaultDueDays: int("defaultDueDays").default(15).notNull(),
  terms: text("terms").notNull(),
  accountCompanyName: varchar("accountCompanyName", { length: 255 }),
  accountNumber: varchar("accountNumber", { length: 128 }),
  accountIfsc: varchar("accountIfsc", { length: 64 }),
  accountBranch: varchar("accountBranch", { length: 255 }),
  logoUrl: text("logoUrl"),
  logoKey: varchar("logoKey", { length: 512 }),
  scannerUrl: text("scannerUrl"),
  scannerKey: varchar("scannerKey", { length: 512 }),
  signatureUrl: text("signatureUrl"),
  signatureKey: varchar("signatureKey", { length: 512 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const invoices = mysqlTable("invoices", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull(),
  invoiceNumber: varchar("invoiceNumber", { length: 32 }).notNull().unique(),
  status: mysqlEnum("status", ["Draft", "Due", "Paid", "Cancelled"]).default("Draft").notNull(),
  clientName: varchar("clientName", { length: 255 }).notNull(),
  clientAddress: text("clientAddress").notNull(),
  clientContact: varchar("clientContact", { length: 64 }),
  clientEmail: varchar("clientEmail", { length: 320 }),
  clientGst: varchar("clientGst", { length: 32 }),
  invoiceDate: varchar("invoiceDate", { length: 32 }).notNull(),
  dueDate: varchar("dueDate", { length: 32 }).notNull(),
  itemsJson: text("itemsJson").notNull(),
  subtotal: decimal("subtotal", { precision: 14, scale: 2 }).notNull(),
  gstRate: decimal("gstRate", { precision: 5, scale: 2 }).notNull(),
  gstMode: mysqlEnum("gstMode", ["inclusive", "exclusive"]).default("exclusive").notNull(),
  gstAmount: decimal("gstAmount", { precision: 14, scale: 2 }).notNull(),
  grandTotal: decimal("grandTotal", { precision: 14, scale: 2 }).notNull(),
  notes: text("notes"),
  terms: text("terms"),
  companyGst: varchar("companyGst", { length: 32 }).notNull(),
  companyAddress: text("companyAddress").notNull(),
  accountCompanyName: varchar("accountCompanyName", { length: 255 }),
  accountNumber: varchar("accountNumber", { length: 128 }),
  accountIfsc: varchar("accountIfsc", { length: 64 }),
  accountBranch: varchar("accountBranch", { length: 255 }),
  logoUrl: text("logoUrl"),
  logoKey: varchar("logoKey", { length: 512 }),
  signatureUrl: text("signatureUrl"),
  signatureKey: varchar("signatureKey", { length: 512 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const receiptSettings = mysqlTable("receiptSettings", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull().unique(),
  companyGst: varchar("companyGst", { length: 32 }).notNull(),
  companyAddress: text("companyAddress").notNull(),
  receiptPrefix: varchar("receiptPrefix", { length: 24 }).default("RCT").notNull(),
  receiptNumberStart: int("receiptNumberStart").default(1).notNull(),
  receiptNumberNext: int("receiptNumberNext").default(1).notNull(),
  terms: text("terms").notNull(),
  accountCompanyName: varchar("accountCompanyName", { length: 255 }),
  accountNumber: varchar("accountNumber", { length: 128 }),
  accountIfsc: varchar("accountIfsc", { length: 64 }),
  accountBranch: varchar("accountBranch", { length: 255 }),
  logoUrl: text("logoUrl"),
  logoKey: varchar("logoKey", { length: 512 }),
  signatureUrl: text("signatureUrl"),
  signatureKey: varchar("signatureKey", { length: 512 }),
  footerCompanyName: varchar("footerCompanyName", { length: 255 }).default("FOR EXPERTAID TECHNOLOGIES PVT LTD."),
  footerMessage: varchar("footerMessage", { length: 255 }).default("Thank you for your business!"),
  qrLabel: varchar("qrLabel", { length: 64 }).default("SCAN & PAY"),
  defaultProductsJson: text("defaultProductsJson"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const receipts = mysqlTable("receipts", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull(),
  receiptNumber: varchar("receiptNumber", { length: 32 }).notNull().unique(),
  status: mysqlEnum("status", ["Issued", "Cancelled"]).default("Issued").notNull(),
  invoiceId: int("invoiceId"),
  invoiceNumber: varchar("invoiceNumber", { length: 32 }),
  clientName: varchar("clientName", { length: 255 }).notNull(),
  clientAddress: text("clientAddress").notNull(),
  clientContact: varchar("clientContact", { length: 64 }),
  clientEmail: varchar("clientEmail", { length: 320 }),
  clientGst: varchar("clientGst", { length: 32 }),
  receiptDate: varchar("receiptDate", { length: 32 }).notNull(),
  paymentDate: varchar("paymentDate", { length: 32 }).notNull(),
  amount: decimal("amount", { precision: 14, scale: 2 }).notNull(),
  itemsJson: text("itemsJson"),
  subtotal: decimal("subtotal", { precision: 14, scale: 2 }),
  gstRate: decimal("gstRate", { precision: 5, scale: 2 }),
  gstMode: mysqlEnum("gstMode", ["inclusive", "exclusive"]),
  gstAmount: decimal("gstAmount", { precision: 14, scale: 2 }),
  grandTotal: decimal("grandTotal", { precision: 14, scale: 2 }),
  paymentMode: mysqlEnum("paymentMode", ["Cash", "UPI", "Bank Transfer", "Card", "Cheque", "Other"]).default("Bank Transfer").notNull(),
  transactionReference: varchar("transactionReference", { length: 128 }),
  receivedFor: varchar("receivedFor", { length: 255 }).notNull(),
  notes: text("notes"),
  terms: text("terms"),
  companyGst: varchar("companyGst", { length: 32 }).notNull(),
  companyAddress: text("companyAddress").notNull(),
  accountCompanyName: varchar("accountCompanyName", { length: 255 }),
  accountNumber: varchar("accountNumber", { length: 128 }),
  accountIfsc: varchar("accountIfsc", { length: 64 }),
  accountBranch: varchar("accountBranch", { length: 255 }),
  logoUrl: text("logoUrl"),
  logoKey: varchar("logoKey", { length: 512 }),
  signatureUrl: text("signatureUrl"),
  signatureKey: varchar("signatureKey", { length: 512 }),
  footerCompanyName: varchar("footerCompanyName", { length: 255 }),
  footerMessage: varchar("footerMessage", { length: 255 }),
  qrLabel: varchar("qrLabel", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type Session = typeof sessions.$inferSelect;
export type InsertSession = typeof sessions.$inferInsert;
export type QuotationSettings = typeof quotationSettings.$inferSelect;
export type InsertQuotationSettings = typeof quotationSettings.$inferInsert;
export type QuotationSettingsData = typeof quotationSettingsData.$inferSelect;
export type ProfileSettingsData = typeof profileSettingsData.$inferSelect;
export type QuotationEditHistory = typeof quotationEditHistory.$inferSelect;
export type InsertQuotationEditHistory = typeof quotationEditHistory.$inferInsert;
export type Quotation = typeof quotations.$inferSelect;
export type InsertQuotation = typeof quotations.$inferInsert;
export type Project = typeof projects.$inferSelect;
export type Client = typeof clients.$inferSelect;
export type InsertClient = typeof clients.$inferInsert;
export type InsertProject = typeof projects.$inferInsert;
export type Agreement = typeof agreements.$inferSelect;
export type InsertAgreement = typeof agreements.$inferInsert;
export type InvoiceSettings = typeof invoiceSettings.$inferSelect;
export type InsertInvoiceSettings = typeof invoiceSettings.$inferInsert;
export type Invoice = typeof invoices.$inferSelect;
export type InsertInvoice = typeof invoices.$inferInsert;
export type ReceiptSettings = typeof receiptSettings.$inferSelect;
export type InsertReceiptSettings = typeof receiptSettings.$inferInsert;
export type Receipt = typeof receipts.$inferSelect;
export type InsertReceipt = typeof receipts.$inferInsert;
