-- Expertaid ERP CRM overall database schema

-- Generated from the current MySQL database. No application data is included.

-- Review this file against the Hostinger database before execution.

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `agreements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `publicToken` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientOwnerName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contactNumber` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(320) COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `noOfStudents` int NOT NULL,
  `perStudentPrice` decimal(12,2) DEFAULT NULL,
  `noOfYearPlan` int NOT NULL,
  `startDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `endDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `totalPrice` decimal(14,2) NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('Pending','Approved','Rejected') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Pending',
  `signatureUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureDate` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `decidedAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `logoUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pricingMode` enum('perStudent','package') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'perStudent',
  `packagePrice` decimal(14,2) DEFAULT NULL,
  `instituteType` enum('School','College','Academy') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'School',
  `branchCoverage` enum('individual','multiple') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'individual',
  `branchCount` int NOT NULL DEFAULT '1',
  `session` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '2026-2027',
  `subtotal` decimal(14,2) NOT NULL DEFAULT '0.00',
  `gstRate` decimal(5,2) NOT NULL DEFAULT '18.00',
  `gstMode` enum('inclusive','exclusive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'exclusive',
  `gstAmount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `projectId` int DEFAULT NULL,
  `clientId` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clientStatus` enum('Active','Inactive','Hold','Cancelled','Renewal','Extended','Closed') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `renewalOfAgreementId` int DEFAULT NULL,
  `renewalType` enum('continuous','sixMonths','oneYear') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `agreements_publicToken_unique` (`publicToken`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=300001;

CREATE TABLE IF NOT EXISTS `clientProducts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `clientId` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `projectId` int DEFAULT NULL,
  `productName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity` decimal(12,2) NOT NULL DEFAULT '1.00',
  `unitPrice` decimal(14,2) NOT NULL,
  `gstRate` decimal(5,2) NOT NULL DEFAULT '0.00',
  `gstMode` enum('inclusive','exclusive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'exclusive',
  `subtotal` decimal(14,2) NOT NULL,
  `gstAmount` decimal(14,2) NOT NULL,
  `totalAmount` decimal(14,2) NOT NULL,
  `paidAmount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `paymentStatus` enum('Pending','Partially Paid','Paid') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Pending',
  `dueDate` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paymentDate` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paymentMode` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transactionReference` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=120001;

CREATE TABLE IF NOT EXISTS `clients` (
  `id` int NOT NULL AUTO_INCREMENT,
  `projectId` int DEFAULT NULL,
  `clientId` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ownerId` int NOT NULL,
  `clientName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientOwnerName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `instituteType` enum('School','College','Academy') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'School',
  `branchCoverage` enum('individual','multiple') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'individual',
  `branchCount` int NOT NULL DEFAULT '1',
  `contactNumber` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(320) COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `noOfStudents` int NOT NULL DEFAULT '0',
  `pricingMode` enum('perStudent','package') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'perStudent',
  `perStudentPrice` decimal(12,2) DEFAULT NULL,
  `packagePrice` decimal(14,2) DEFAULT NULL,
  `noOfYearPlan` int NOT NULL DEFAULT '1',
  `startDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `endDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `session` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '2026-2027',
  `totalPrice` decimal(14,2) NOT NULL DEFAULT '0.00',
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('Active','Inactive','Hold','Cancelled','Renewal','Extended','Closed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Active',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `price` decimal(14,2) NOT NULL DEFAULT '0.00',
  `gstRate` decimal(5,2) NOT NULL DEFAULT '18.00',
  `gstMode` enum('inclusive','exclusive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'exclusive',
  `gstAmount` decimal(14,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `clients_clientId_unique` (`clientId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=60001;

CREATE TABLE IF NOT EXISTS `invoiceSettings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `companyGst` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyAddress` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `invoicePrefix` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'INV',
  `invoiceNumberStart` int NOT NULL DEFAULT '1',
  `invoiceNumberNext` int NOT NULL DEFAULT '1',
  `gstRate` decimal(5,2) NOT NULL DEFAULT '18.00',
  `gstMode` enum('inclusive','exclusive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'exclusive',
  `defaultDueDays` int NOT NULL DEFAULT '15',
  `terms` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `accountCompanyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountNumber` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountIfsc` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountBranch` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scannerUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scannerKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `invoiceSettings_ownerId_unique` (`ownerId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=30001;

CREATE TABLE IF NOT EXISTS `invoices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `invoiceNumber` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('Draft','Due','Paid','Cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Draft',
  `clientName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientAddress` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientContact` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clientEmail` varchar(320) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clientGst` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoiceDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dueDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `itemsJson` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `subtotal` decimal(14,2) NOT NULL,
  `gstRate` decimal(5,2) NOT NULL,
  `gstMode` enum('inclusive','exclusive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'exclusive',
  `gstAmount` decimal(14,2) NOT NULL,
  `grandTotal` decimal(14,2) NOT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `terms` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyGst` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyAddress` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `accountCompanyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountNumber` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountIfsc` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountBranch` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `clientId` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `projectId` int DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `invoices_invoiceNumber_unique` (`invoiceNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=120001;

CREATE TABLE IF NOT EXISTS `paymentPlanTerms` (
  `id` int NOT NULL AUTO_INCREMENT,
  `paymentPlanId` int NOT NULL,
  `label` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dueDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount` decimal(14,2) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=30001;

CREATE TABLE IF NOT EXISTS `paymentPlans` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `clientId` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `projectId` int DEFAULT NULL,
  `paymentCycle` enum('single','terms','installments','months') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'installments',
  `totalAmount` decimal(14,2) NOT NULL,
  `initialPayment` decimal(14,2) NOT NULL DEFAULT '0.00',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=30001;

CREATE TABLE IF NOT EXISTS `profileSettingsData` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `profileJson` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `profileSettingsData_ownerId_unique` (`ownerId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=150001;

CREATE TABLE IF NOT EXISTS `projects` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientIdPrefix` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientIdStart` int NOT NULL DEFAULT '1',
  `nextClientId` int NOT NULL DEFAULT '1',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isMain` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=60001;

CREATE TABLE IF NOT EXISTS `quotationEditHistory` (
  `id` int NOT NULL AUTO_INCREMENT,
  `quotationId` int NOT NULL,
  `ownerId` int NOT NULL,
  `editedBy` int NOT NULL,
  `editedByName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `editedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `snapshotJson` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=360001;

CREATE TABLE IF NOT EXISTS `quotationSettings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `companyGst` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyAddress` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `validityDays` int NOT NULL DEFAULT '15',
  `gstRate` decimal(5,2) NOT NULL DEFAULT '18.00',
  `terms` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `productsJson` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `logoUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scannerUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scannerKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `gstMode` enum('inclusive','exclusive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'exclusive',
  `invoiceNumberStart` int NOT NULL DEFAULT '129',
  `invoiceNumberNext` int NOT NULL DEFAULT '129',
  `quotationPrefix` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'QT',
  `accountCompanyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountNumber` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountIfsc` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountBranch` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `quotationSettings_ownerId_unique` (`ownerId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=690001;

CREATE TABLE IF NOT EXISTS `quotationSettingsData` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `settingsJson` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `quotationSettingsData_ownerId_unique` (`ownerId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=120001;

CREATE TABLE IF NOT EXISTS `quotations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `quotationNumber` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientAddress` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientContact` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientEmail` varchar(320) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clientGst` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quotationDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `validityDays` int NOT NULL DEFAULT '15',
  `companyGst` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyAddress` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `itemsJson` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `subtotal` decimal(14,2) NOT NULL,
  `gstRate` decimal(5,2) NOT NULL,
  `gstAmount` decimal(14,2) NOT NULL,
  `grandTotal` decimal(14,2) NOT NULL,
  `terms` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scannerUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scannerKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `gstMode` enum('inclusive','exclusive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'exclusive',
  `lastEditedBy` int DEFAULT NULL,
  `lastEditedByName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastEditedAt` timestamp NULL DEFAULT NULL,
  `invoiceNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `estimationNumber` int NOT NULL DEFAULT '1',
  `accountCompanyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountNumber` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountIfsc` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountBranch` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('Awaiting','Success','Closed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Awaiting',
  `logoUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `quotations_quotationNumber_unique` (`quotationNumber`),
  UNIQUE KEY `quotations_invoiceNumber_unique` (`invoiceNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=360001;

CREATE TABLE IF NOT EXISTS `receiptSettings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `companyGst` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyAddress` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `receiptPrefix` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'RCT',
  `receiptNumberStart` int NOT NULL DEFAULT '1',
  `receiptNumberNext` int NOT NULL DEFAULT '1',
  `terms` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `accountCompanyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountNumber` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountIfsc` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountBranch` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `footerCompanyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'FOR EXPERTAID TECHNOLOGIES PVT LTD.',
  `footerMessage` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'Thank you for your business!',
  `qrLabel` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT 'SCAN & PAY',
  `defaultProductsJson` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `receiptSettings_ownerId_unique` (`ownerId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=30001;

CREATE TABLE IF NOT EXISTS `receipts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `receiptNumber` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('Issued','Cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Issued',
  `clientName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientAddress` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `clientContact` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clientEmail` varchar(320) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `receiptDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `paymentDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount` decimal(14,2) NOT NULL,
  `paymentMode` enum('Cash','UPI','Bank Transfer','Card','Cheque','Other') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Bank Transfer',
  `transactionReference` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `receivedFor` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `terms` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyGst` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyAddress` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `accountCompanyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountNumber` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountIfsc` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accountBranch` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logoKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signatureKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `invoiceId` int DEFAULT NULL,
  `invoiceNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clientGst` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `itemsJson` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subtotal` decimal(14,2) DEFAULT NULL,
  `gstRate` decimal(5,2) DEFAULT NULL,
  `gstMode` enum('inclusive','exclusive') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gstAmount` decimal(14,2) DEFAULT NULL,
  `grandTotal` decimal(14,2) DEFAULT NULL,
  `footerCompanyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `footerMessage` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qrLabel` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clientId` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `receipts_receiptNumber_unique` (`receiptNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=270001;

CREATE TABLE IF NOT EXISTS `sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ownerId` int NOT NULL,
  `sessionLabel` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `startDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `endDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=60001;

CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `openId` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(320) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `loginMethod` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` enum('user','admin') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'user',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastSignedIn` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `companyLogoUrl` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyLogoKey` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `serviceCaption` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `footerCompanyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sessionMode` enum('all','single') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'single',
  `currentSession` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '2026-2027',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `users_openId_unique` (`openId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=13800001;

SET FOREIGN_KEY_CHECKS = 1;
